/// sound files ///
function ring1() { document.getElementById("oshigotoOtsukaresama_sasayaki.mp3").play(); }
function ring2() { document.getElementById("oyasuminasai_sasayaki.mp3").play(); }
function ring3() { document.getElementById("1syukanOtsukaresama.mp3").play(); }
function ring4() { document.getElementById("aruchuCaffeechuPomenimuchu.mp3").play(); }
function ring5() { document.getElementById("hanamizuZubizubiRikochan.mp3").play(); }
function ring6() { document.getElementById("konbanha.mp3").play(); }
function ring7() { document.getElementById("oyasumi.mp3").play(); }
function ring8() { document.getElementById("oyasumi_hanagoe.mp3").play(); }
function ring9() { document.getElementById("RikoNote.mp3").play(); }
function ring10() { document.getElementById("baka.mp3").play(); } //admiration
function ring11() { document.getElementById("barebaredayo.mp3").play(); }
function ring12() { document.getElementById("butigire.mp3").play(); }
function ring13() { document.getElementById("capcomYorosiku.mp3").play(); }
function ring14() { document.getElementById("choshieena.mp3").play(); }
function ring15() { document.getElementById("chottoMaji.mp3").play(); }
function ring16() { document.getElementById("damatteMattokeAHO.mp3").play(); }
function ring17() { document.getElementById("fullHPChu.mp3").play(); }
function ring18() { document.getElementById("gomenNasaiYurushite.mp3").play(); }
function ring19() { document.getElementById("hayakuchi.mp3").play(); }
function ring20() { document.getElementById("jikoshokai.mp3").play(); }
function ring21() { document.getElementById("kimo.mp3").play(); }
function ring22() { document.getElementById("kimochiwarui.mp3").play(); }
function ring23() { document.getElementById("konitiwa.mp3").play(); }
function ring24() { document.getElementById("kusogayo.mp3").play(); }
function ring25() { document.getElementById("onegaisimasu.mp3").play(); }
function ring26() { document.getElementById("sya-naina-.mp3").play(); }
function ring27() { document.getElementById("tadaima.mp3").play(); }
function ring28() { document.getElementById("uchutoKoshin.mp3").play(); }
function ring29() { document.getElementById("konnichiha_echo.mp3").play(); }
function ring30() { document.getElementById("arigatone.mp3").play(); }
function ring31() { document.getElementById("arigatone2.mp3").play(); }
function ring32() { document.getElementById("kochirakosoKansha.mp3").play(); }
function ring33() { document.getElementById("usojan.mp3").play(); }

function ring34() { document.getElementById("ninnin.mp3").play(); }
function ring35() { document.getElementById("nomimono.mp3").play(); }
function ring36() { document.getElementById("okay001.mp3").play(); }
function ring37() { document.getElementById("okay002.mp3").play(); }
function ring38() { document.getElementById("senpai1.mp3").play(); }
function ring39() { document.getElementById("senpai2.mp3").play(); }
function ring40() { document.getElementById("senpai3.mp3").play(); }
function ring41() { document.getElementById("senpai4.mp3").play(); }
function ring42() { document.getElementById("senpai5.mp3").play(); }
function ring43() { document.getElementById("senpai6.mp3").play(); }
function ring44() { document.getElementById("shinuttebouyomityan.mp3").play(); }
function ring45() { document.getElementById("shit.mp3").play(); }
function ring46() { document.getElementById("suimasen1.mp3").play(); }
function ring47() { document.getElementById("suimasen2.mp3").play(); }
function ring48() { document.getElementById("suimasen3.mp3").play(); }
function ring49() { document.getElementById("tsuyoizo.mp3").play(); }
function ring50() { document.getElementById("uhoho.mp3").play(); }
function ring51() { document.getElementById("umaireina.mp3").play(); }
function ring52() { document.getElementById("waruihito.mp3").play(); }
function ring53() { document.getElementById("yabai.mp3").play(); }
function ring54() { document.getElementById("yamero.mp3").play(); }
function ring55() { document.getElementById("yamero2.mp3").play(); }
function ring56() { document.getElementById("onegaishimasu.mp3").play(); }
function ring57() { document.getElementById("toireshitaimoreru.mp3").play(); }
function ring58() { document.getElementById("karasu_with_atarukun.mp3").play(); }
function ring59() { document.getElementById("karasu1.mp3").play(); }
function ring60() { document.getElementById("karasu2.mp3").play(); }
function ring61() { document.getElementById("karasu3.mp3").play(); }
function ring62() { document.getElementById("koroshityau.mp3").play(); }
function ring63() { document.getElementById("kushami1.mp3").play(); }
function ring64() { document.getElementById("noah1.mp3").play(); }
function ring65() { document.getElementById("oshikko1.mp3").play(); }
function ring66() { document.getElementById("mamomamo.mp3").play(); }
function ring67() { document.getElementById("morasitemoii.mp3").play(); }
function ring68() { document.getElementById("outlast1.mp3").play(); }
function ring69() { document.getElementById("outlast2.mp3").play(); }
function ring70() { document.getElementById("bokuwotaosuhukanou.mp3").play(); }
function ring71() { document.getElementById("gomi.mp3").play(); }
function ring72() { document.getElementById("nicetryxq2.mp3").play(); }
function ring73() { document.getElementById("obakun1.mp3").play(); }
function ring74() { document.getElementById("obakun2.mp3").play(); }
function ring75() { document.getElementById("obakun3.mp3").play(); }
function ring76() { document.getElementById("omae.mp3").play(); }
function ring77() { document.getElementById("orehatenz.mp3").play(); }

function ring81() { document.getElementById("xqtamago.mp3").play(); }
function ring82() { document.getElementById("kansha1.mp3").play(); }
function ring83() { document.getElementById("kyouchan1.mp3").play(); }
function ring84() { document.getElementById("usotuke.mp3").play(); }
function ring85() { document.getElementById("crosshairminai.mp3").play(); }
function ring86() { document.getElementById("gooya.mp3").play(); }
function ring87() { document.getElementById("hukai1.mp3").play(); }
function ring88() { document.getElementById("motitsumotaretsu1.mp3").play(); }
function ring89() { document.getElementById("motitsumotaretsu2.mp3").play(); }
function ring90() { document.getElementById("motitsumotaretsu3.mp3").play(); }
function ring91() { document.getElementById("motitsumotaretsu4.mp3").play(); }
function ring92() { document.getElementById("renshuu.mp3").play(); }
function ring93() { document.getElementById("shoukinkubi.mp3").play(); }
function ring94() { document.getElementById("tugikarakiwotukeru.mp3").play(); }
function ring95() { document.getElementById("g7scout.mp3").play(); }
function ring97() { document.getElementById("jaana1.mp3").play(); }
function ring98() { document.getElementById("kusoaimshita.mp3").play(); }
function ring99() { document.getElementById("nicetryxq1.mp3").play(); }
function ring100() { document.getElementById("chigauchigau.mp3").play(); }
function ring101() { document.getElementById("daijoubu.mp3").play(); }
function ring102() { document.getElementById("jasperjasperjasper.mp3").play(); }
function ring103() { document.getElementById("maamaamaamaa.mp3").play(); }
function ring104() { document.getElementById("makasero1.mp3").play(); }
function ring105() { document.getElementById("makasero2.mp3").play(); }
function ring106() { document.getElementById("makasero3.mp3").play(); }
function ring107() { document.getElementById("wahahadon.mp3").play(); }
function ring108() { document.getElementById("rikojoy_1syukanOtsukaresama.mp3").play(); } //aisatsu
function ring109() { document.getElementById("lol1.mp3").play(); }
function ring110() { document.getElementById("udon_karaage1.mp3").play(); }
function ring115() { document.getElementById("corn5.mp3").play(); }
function ring122() { document.getElementById("shussho.mp3").play(); }
function ring123() { document.getElementById("lemon.mp3").play(); }
function ring124() { document.getElementById("kimetsunoyaiba.mp3").play(); }
function ring125() { document.getElementById("opopopop.mp3").play(); }
function ring126() { document.getElementById("omapro.mp3").play(); }
function ring127() { document.getElementById("noahnidereru.mp3").play(); }
function ring128() { document.getElementById("zamaa.mp3").play(); }
function ring130() { document.getElementById("danmatsuma.mp3").play(); }
function ring131() { document.getElementById("tsuraitokikoso1.mp3").play(); }
function ring132() { document.getElementById("tsuraitokikoso2.mp3").play(); }
function ring133() { document.getElementById("valouma.mp3").play(); }
function ring134() { document.getElementById("ha_ka_ha.mp3").play(); }
function ring135() { document.getElementById("baw1.mp3").play(); }
function ring136() { document.getElementById("baw2.mp3").play(); }
function ring137() { document.getElementById("reinayane.mp3").play(); }
function ring138() { document.getElementById("iitachimawari.mp3").play(); }
function ring139() { document.getElementById("tasukete.mp3").play(); }
function ring140() { document.getElementById("aruaru.mp3").play(); }
function ring141() { document.getElementById("zepher.mp3").play(); }
function ring142() { document.getElementById("hacchimi1.mp3").play(); }
function ring143() { document.getElementById("hacchimi2.mp3").play(); }

function ring145() { document.getElementById("niwatori.mp3").play(); }
function ring147() { document.getElementById("fuifui.mp3").play(); }
function ring148() { document.getElementById("tenjoukowashita.mp3").play(); }
function ring149() { document.getElementById("pawaharajoushi.mp3").play(); }
function ring150() { document.getElementById("omedetou.mp3").play(); }
function ring151() { document.getElementById("ow_anyon.mp3").play(); }
function ring152() { document.getElementById("jaspakeisuke.mp3").play(); }
function ring153() { document.getElementById("shinekoshinetanjent.mp3").play(); }
function ring154() { document.getElementById("ow_vc_uta.mp3").play(); }
function ring155() { document.getElementById("nukerenai.mp3").play(); }
function ring156() { document.getElementById("warai2.mp3").play(); }
function ring158() { document.getElementById("carry_mode2.mp3").play(); }
function ring159() { document.getElementById("carry_mode1.mp3").play(); }
function ring160() { document.getElementById("oomutakenkei.mp3").play(); }
function ring161() { document.getElementById("outlast3.mp3").play(); }
function ring162() { document.getElementById("esportsmorudo.mp3").play(); }
function ring163() { document.getElementById("kansha3.mp3").play(); }
function ring164() { document.getElementById("100cut.mp3").play(); }
function ring165() { document.getElementById("motaretsu.mp3").play(); }
function ring166() { document.getElementById("mirai2.mp3").play(); }
function ring167() { document.getElementById("mirai3.mp3").play(); }
function ring168() { document.getElementById("breeze.mp3").play(); }
function ring169() { document.getElementById("nandayo.mp3").play(); }
function ring170() { document.getElementById("oretatinoisshuukan.mp3").play(); }
function ring171() { document.getElementById("4ninkousoku.mp3").play(); }
function ring172() { document.getElementById("aa2.mp3").play(); }
function ring173() { document.getElementById("ass.mp3").play(); }
function ring174() { document.getElementById("karasu4.mp3").play(); }
function ring175() { document.getElementById("karasu5.mp3").play(); }
function ring176() { document.getElementById("karasu6.mp3").play(); }
function ring179() { document.getElementById("usagisan1.mp3").play(); }
function ring180() { document.getElementById("geijutsu.mp3").play(); }
function ring181() { document.getElementById("karasu9.mp3").play(); }
function ring182() { document.getElementById("karasu10.mp3").play(); }
function ring183() { document.getElementById("e2.mp3").play(); }
function ring184() { document.getElementById("eeee.mp3").play(); }
function ring185() { document.getElementById("karasu11.mp3").play(); }
function ring186() { document.getElementById("dfdfdfdf.mp3").play(); }
function ring187() { document.getElementById("lfg.mp3").play(); }
function ring188() { document.getElementById("youareago.mp3").play(); }
function ring189() { document.getElementById("mama.mp3").play(); }
function ring190() { document.getElementById("tobutameniha.mp3").play(); }
function ring191() { document.getElementById("byunsuka.mp3").play(); }
function ring192() { document.getElementById("agohan.mp3").play(); }
function ring193() { document.getElementById("bleach.mp3").play(); }
function ring194() { document.getElementById("motitsumotaretsu5.mp3").play(); }
function ring195() { document.getElementById("motitsumotaretsu6.mp3").play(); }
function ring196() { document.getElementById("24hhaishin.mp3").play(); }
function ring197() { document.getElementById("haan.mp3").play(); }
function ring198() { document.getElementById("kimotiii1.mp3").play(); }
function ring199() { document.getElementById("ace1_icebox.mp3").play(); }
function ring200() { document.getElementById("ace2_split.mp3").play(); }
function ring201() { document.getElementById("ace3_haven.mp3").play(); }
function ring202() { document.getElementById("ace4_split.mp3").play(); }
function ring203() { document.getElementById("judgeacedasai.mp3").play(); }
function ring204() { document.getElementById("a3na.mp3").play(); }
function ring205() { document.getElementById("tsugihaoresasatik.mp3").play(); }
function ring206() { document.getElementById("usagisan2.mp3").play(); }
function ring207() { document.getElementById("jasudamu1.mp3").play(); }
function ring209() { document.getElementById("window.mp3").play(); }
function ring210() { document.getElementById("nyaanyaa.mp3").play(); }
function ring211() { document.getElementById("fujiisouta.mp3").play(); }
function ring212() { document.getElementById("yeahyeah.mp3").play(); }
function ring213() { document.getElementById("momu.mp3").play(); }
function ring214() { document.getElementById("nankohara.mp3").play(); }
function ring215() { document.getElementById("majitsuyoi.mp3").play(); }
function ring216() { document.getElementById("kuraeee.mp3").play(); }
function ring217() { document.getElementById("jasuka.mp3").play(); }
function ring218() { document.getElementById("gorira.mp3").play(); }
function ring219() { document.getElementById("ace_misui_1.mp3").play(); }
function ring220() { document.getElementById("yadaa2.mp3").play(); }
function ring221() { document.getElementById("uhuhu.mp3").play(); }
function ring222() { document.getElementById("reinayanke.mp3").play(); }
function ring223() { document.getElementById("kudokimonku.mp3").play(); }
function ring224() { document.getElementById("ganbarudo.mp3").play(); }
function ring225() { document.getElementById("edo1.mp3").play(); }
function ring226() { document.getElementById("edo2.mp3").play(); }
function ring227() { document.getElementById("pottyama.mp3").play(); }
function ring228() { document.getElementById("guufii.mp3").play(); }
function ring229() { document.getElementById("chehonmang.mp3").play(); }
function ring230() { document.getElementById("aan_tasukete.mp3").play(); }
function ring231() { document.getElementById("hato1.mp3").play(); }
function ring232() { document.getElementById("hato2.mp3").play(); }
function ring233() { document.getElementById("hato3.mp3").play(); }
function ring234() { document.getElementById("nankaippaitobideta.mp3").play(); }
function ring235() { document.getElementById("onlyone_ore.mp3").play(); }
function ring236() { document.getElementById("kanooto.mp3").play(); }
function ring237() { document.getElementById("usagisan3.mp3").play(); }
function ring238() { document.getElementById("projan.mp3").play(); }
function ring239() { document.getElementById("kanjougashinderuowatteru.mp3").play(); }
function ring240() { document.getElementById("daisukiminna.mp3").play(); }
function ring241() { document.getElementById("koikoikoikoi.mp3").play(); }
function ring242() { document.getElementById("menimenidash.mp3").play(); }
function ring243() { document.getElementById("paa.mp3").play(); }
function ring244() { document.getElementById("pi.mp3").play(); }
function ring245() { document.getElementById("nice001.mp3").play(); }
function ring246() { document.getElementById("budoutou.mp3").play(); }
function ring247() { document.getElementById("axtuaxtuaxtu.mp3").play(); }
function ring248() { document.getElementById("francisco1.mp3").play(); }
function ring249() { document.getElementById("francisco2.mp3").play(); }
function ring250() { document.getElementById("karasu12.mp3").play(); }
function ring251() { document.getElementById("hato4.mp3").play(); }
function ring252() { document.getElementById("dekai1.mp3").play(); }
function ring253() { document.getElementById("dekai2.mp3").play(); }
function ring254() { document.getElementById("kanojotowakareta.mp3").play(); }
function ring255() { document.getElementById("boe.mp3").play(); }
function ring256() { document.getElementById("wtf.mp3").play(); }
function ring257() { document.getElementById("hato5.mp3").play(); }
function ring258() { document.getElementById("udon_karaage2.mp3").play(); }
function ring259() { document.getElementById("ponpon.mp3").play(); }
function ring260() { document.getElementById("jasudamu3.mp3").play(); }
function ring261() { document.getElementById("ago_breeze.mp3").play(); }
function ring262() { document.getElementById("jimennisuityaku.mp3").play(); }
function ring263() { document.getElementById("makasetehirontoni.mp3").play(); }
function ring264() { document.getElementById("2100yen.mp3").play(); }
function ring265() { document.getElementById("oshikko2.mp3").play(); }
function ring266() { document.getElementById("uwaaaa.mp3").play(); }

function ring268() { document.getElementById("kurochan1.mp3").play(); }
function ring269() { document.getElementById("obakun_clutch.mp3").play(); }
function ring270() { document.getElementById("rassya1.mp3").play(); }
function ring271() { document.getElementById("mezamerotashima.mp3").play(); }
function ring272() { document.getElementById("karasu13.mp3").play(); }
function ring273() { document.getElementById("karasu14.mp3").play(); }
function ring274() { document.getElementById("jnoope.mp3").play(); }
function ring275() { document.getElementById("kaijosuru.mp3").play(); }
function ring276() { document.getElementById("kaisetsu.mp3").play(); }
function ring277() { document.getElementById("yabai2.mp3").play(); }
function ring278() { document.getElementById("uwaaaa2.mp3").play(); }
function ring279() { document.getElementById("rantashi.mp3").play(); }
function ring280() { document.getElementById("showerdestroy.mp3").play(); }
function ring281() { document.getElementById("haa.mp3").play(); }
function ring282() { document.getElementById("daijoubu2.mp3").play(); }
function ring283() { document.getElementById("kamyu1.mp3").play(); }
function ring284() { document.getElementById("kamyu2.mp3").play(); }
function ring285() { document.getElementById("yokubouwokaihoushiro.mp3").play(); }
function ring286() { document.getElementById("51238.mp3").play(); }
function ring287() { document.getElementById("aaoetsu.mp3").play(); }
function ring288() { document.getElementById("opereetaawakaran.mp3").play(); }
function ring289() { document.getElementById("mou.mp3").play(); }
function ring290() { document.getElementById("eguite2.mp3").play(); }
function ring291() { document.getElementById("eguite3.mp3").play(); }
function ring292() { document.getElementById("baw3.mp3").play(); }
function ring293() { document.getElementById("zakenna.mp3").play(); }
function ring294() { document.getElementById("kamyuuu.mp3").play(); }
function ring295() { document.getElementById("oooh.mp3").play(); }
function ring296() { document.getElementById("ohho001.mp3").play(); }
function ring297() { document.getElementById("kyundesu.mp3").play(); }
function ring298() { document.getElementById("ggyanke.mp3").play(); }
function ring299() { document.getElementById("f1.mp3").play(); }
function ring300() { document.getElementById("tashimageigo.mp3").play(); }
function ring301() { document.getElementById("to.mp3").play(); }
function ring304() { document.getElementById("ohho002.mp3").play(); }
function ring305() { document.getElementById("ohho003.mp3").play(); }
function ring306() { document.getElementById("eguite4.mp3").play(); }
function ring307() { document.getElementById("surarin.mp3").play(); }
function ring308() { document.getElementById("zettaisubetteru.mp3").play(); }
function ring309() { document.getElementById("777.mp3").play(); }
function ring310() { document.getElementById("ahaha.mp3").play(); }
function ring311() { document.getElementById("barbarbar.mp3").play(); }
function ring312() { document.getElementById("eeeeee.mp3").play(); }
function ring313() { document.getElementById("extuextuextu.mp3").play(); }
function ring314() { document.getElementById("fextu.mp3").play(); }
function ring315() { document.getElementById("hadou90.mp3").play(); }
function ring316() { document.getElementById("ihihi.mp3").play(); }
function ring317() { document.getElementById("ittakasurarinyoshi.mp3").play(); }
function ring318() { document.getElementById("joyman.mp3").play(); }
function ring319() { document.getElementById("kajino_karasu.mp3").play(); }
function ring320() { document.getElementById("kajinoomoroiyan.mp3").play(); }
function ring321() { document.getElementById("kareepan.mp3").play(); }
function ring322() { document.getElementById("kuso.mp3").play(); }
function ring323() { document.getElementById("kusoga.mp3").play(); }
function ring324() { document.getElementById("tabako.mp3").play(); }
function ring325() { document.getElementById("suika.mp3").play(); }
function ring326() { document.getElementById("nande20.mp3").play(); }
function ring327() { document.getElementById("kityaaa.mp3").play(); }
function ring328() { document.getElementById("jikki_moteru.mp3").play(); }
function ring329() { document.getElementById("hisshisugi.mp3").play(); }
function ring330() { document.getElementById("bgmbgmbgm.mp3").play(); }
function ring331() { document.getElementById("aha_hha.mp3").play(); }
function ring332() { document.getElementById("777bar.mp3").play(); }
function ring333() { document.getElementById("rippanayuusha.mp3").play(); }
function ring334() { document.getElementById("subetta.mp3").play(); }
function ring335() { document.getElementById("boss1.mp3").play(); }
function ring336() { document.getElementById("laboikube.mp3").play(); }
function ring337() { document.getElementById("usojaaa.mp3").play(); }
function ring338() { document.getElementById("wonmutago1.mp3").play(); }
function ring339() { document.getElementById("atama2.mp3").play(); }
function ring340() { document.getElementById("ponponponpon.mp3").play(); }
function ring341() { document.getElementById("tanomuike.mp3").play(); }
function ring342() { document.getElementById("shoubugotomigi.mp3").play(); }
function ring343() { document.getElementById("saiakuda.mp3").play(); }
function ring344() { document.getElementById("a_mar_gorioshi.mp3").play(); }
function ring345() { document.getElementById("ibaraki_tochigi.mp3").play(); }
function ring346() { document.getElementById("kyoto.mp3").play(); }
function ring347() { document.getElementById("dosue.mp3").play(); }
function ring348() { document.getElementById("321pon.mp3").play(); }
function ring349() { document.getElementById("pi_sutasuta.mp3").play(); }
function ring350() { document.getElementById("kusobukisenshuken.mp3").play(); }
function ring351() { document.getElementById("damare.mp3").play(); }
function ring352() { document.getElementById("slot_freeze.mp3").play(); }
function ring353() { document.getElementById("atama3.mp3").play(); }
function ring354() { document.getElementById("arayotto.mp3").play(); }
function ring355() { document.getElementById("gongtempestkunrin.mp3").play(); }
function ring356() { document.getElementById("migijanaino.mp3").play(); }
function ring358() { document.getElementById("shinyanoskulltown.mp3").play(); }
function ring360() { document.getElementById("jasdesu1.mp3").play(); }
function ring361() { document.getElementById("jasdesu2.mp3").play(); }
function ring362() { document.getElementById("okaeritadaima.mp3").play(); }
function ring363() { document.getElementById("anyon.mp3").play(); }
function ring364() { document.getElementById("seiyacorn.mp3").play(); }
function ring366() { document.getElementById("sukesuke.mp3").play(); }
function ring367() { document.getElementById("yabasugiw.mp3").play(); }
function ring368() { document.getElementById("anatatekini.mp3").play(); }
function ring369() { document.getElementById("ee_masuosan.mp3").play(); }
function ring370() { document.getElementById("kurojanaishirodakedokuro.mp3").play(); }
function ring371() { document.getElementById("nakanosotono.mp3").play(); }
function ring372() { document.getElementById("cheeserifle.mp3").play(); }
function ring373() { document.getElementById("karasu15.mp3").play(); }
function ring374() { document.getElementById("karasu16.mp3").play(); }
function ring375() { document.getElementById("gomidoujou.mp3").play(); }
function ring376() { document.getElementById("donokuninisundoru.mp3").play(); }
function ring377() { document.getElementById("pon.mp3").play(); }
function ring378() { document.getElementById("happy_oneday.mp3").play(); }
function ring379() { document.getElementById("dofree.mp3").play(); }
function ring380() { document.getElementById("poooh.mp3").play(); }
function ring381() { document.getElementById("kuhahahaha.mp3").play(); }
function ring382() { document.getElementById("fooo.mp3").play(); }
function ring383() { document.getElementById("yattadee.mp3").play(); }
function ring384() { document.getElementById("vodka_hontou.mp3").play(); }
function ring385() { document.getElementById("hanya001.mp3").play(); }
function ring386() { document.getElementById("hanya002.mp3").play(); }
function ring387() { document.getElementById("hanya003.mp3").play(); }
function ring388() { document.getElementById("hanya004.mp3").play(); }
function ring389() { document.getElementById("hanyapoyo001.mp3").play(); }
function ring390() { document.getElementById("ojisanyane.mp3").play(); }
function ring391() { document.getElementById("eguite5.mp3").play(); }
function ring392() { document.getElementById("eguite6.mp3").play(); }
function ring393() { document.getElementById("eguite7.mp3").play(); }
function ring394() { document.getElementById("eguite8.mp3").play(); }
function ring395() { document.getElementById("mei_install.mp3").play(); }
function ring396() { document.getElementById("mei_finaleternal.mp3").play(); }
function ring397() { document.getElementById("h_pillowtalk.mp3").play(); }
function ring398() { document.getElementById("wall_tashima.mp3").play(); }
function ring399() { document.getElementById("fa_bck.mp3").play(); }
function ring400() { document.getElementById("fujiwara.mp3").play(); }
function ring401() { document.getElementById("yuigadokuson1.mp3").play(); }
function ring402() { document.getElementById("tsu_souhanaran.mp3").play(); }
function ring403() { document.getElementById("tsu_kopipe.mp3").play(); }
function ring404() { document.getElementById("tsu_gomikyaku.mp3").play(); }
function ring405() { document.getElementById("eguite9.mp3").play(); }
function ring406() { document.getElementById("satoshinipikachu.mp3").play(); }
function ring407() { document.getElementById("jaspakeisuke.mp3").play(); }
function ring408() { document.getElementById("karasu17.mp3").play(); }
function ring410() { document.getElementById("moudamepo.mp3").play(); }
function ring412() { document.getElementById("naepoyo.mp3").play(); }
function ring413() { document.getElementById("sharutan.mp3").play(); }
function ring414() { document.getElementById("hanya005.mp3").play(); }
function ring415() { document.getElementById("hanya006.mp3").play(); }
function ring416() { document.getElementById("etsudesu01.mp3").play(); }
function ring417() { document.getElementById("bleach_orihime.mp3").play(); }
function ring418() { document.getElementById("un_mp7.mp3").play(); }
function ring419() { document.getElementById("etsudesu02.mp3").play(); }
function ring420() { document.getElementById("tsu_tashik1.mp3").play(); }
function ring421() { document.getElementById("tsu_tashik2.mp3").play(); }
function ring422() { document.getElementById("tsu_reakshakakintv.mp3").play(); }
function ring424() { document.getElementById("un_welcometashimafam.mp3").play(); }
function ring425() { document.getElementById("un_onnazaurusu.mp3").play(); }
function ring426() { document.getElementById("un_jaspercent.mp3").play(); }
function ring427() { document.getElementById("agolishnoob.mp3").play(); }
function ring428() { document.getElementById("mei_africapie.mp3").play(); }
function ring429() { document.getElementById("h_ketaikannou.mp3").play(); }
function ring430() { document.getElementById("tynoahsama.mp3").play(); }
function ring431() { document.getElementById("soulchamp.mp3").play(); }
function ring433() { document.getElementById("gesuiman.mp3").play(); }
function ring434() { document.getElementById("mowmowmow.mp3").play(); }
function ring435() { document.getElementById("yesyesyes.mp3").play(); }
function ring436() { document.getElementById("hevun_nasai.mp3").play(); }
function ring437() { document.getElementById("pon_tuyooo.mp3").play(); }
function ring438() { document.getElementById("relaxrelaxrelax.mp3").play(); }
function ring439() { document.getElementById("compeitou.mp3").play(); }
function ring440() { document.getElementById("kamigee.mp3").play(); }
function ring441() { document.getElementById("eguite010.mp3").play(); }
function ring442() { document.getElementById("re_doryoku.mp3").play(); }
function ring443() { document.getElementById("atama_nasaso.mp3").play(); }
function ring444() { document.getElementById("achadayonepocchama.mp3").play(); }
function ring445() { document.getElementById("sushizanmai.mp3").play(); }
function ring446() { document.getElementById("kakuseishitajasper.mp3").play(); }
function ring447() { document.getElementById("iijo.mp3").play(); }
function ring448() { document.getElementById("orelaz.mp3").play(); }
function ring449() { document.getElementById("h_openy.mp3").play(); }
function ring450() { document.getElementById("beau_reina.mp3").play(); }
function ring451() { document.getElementById("aiyaaa.mp3").play(); }
function ring452() { document.getElementById("tenzmiteruka.mp3").play(); }
function ring453() { document.getElementById("nice002.mp3").play(); }
function ring454() { document.getElementById("hato6.mp3").play(); }
function ring455() { document.getElementById("hato7.mp3").play(); }
function ring456() { document.getElementById("dhukushi.mp3").play(); }
function ring457() { document.getElementById("lol2.mp3").play(); }
function ring458() { document.getElementById("h_mouman.mp3").play(); }
function ring459() { document.getElementById("h_oshiride.mp3").play(); }
function ring460() { document.getElementById("h_dd.mp3").play(); }
function ring461() { document.getElementById("naruhodonyancats001.mp3").play(); }
function ring462() { document.getElementById("naruhodonyancats002.mp3").play(); }
function ring463() { document.getElementById("omaenorebanira.mp3").play(); }
function ring464() { document.getElementById("supaobapiku.mp3").play(); }
function ring465() { document.getElementById("pepper_shishou.mp3").play(); }
function ring466() { document.getElementById("jett_sutanmijpn.mp3").play(); }
function ring467() { document.getElementById("lenz2.mp3").play(); }
function ring468() { document.getElementById("senmenjo.mp3").play(); }
function ring469() { document.getElementById("esportsmode001.mp3").play(); }
function ring470() { document.getElementById("setshiteikimasu.mp3").play(); }
function ring471() { document.getElementById("jasdesu3.mp3").play(); }
function ring472() { document.getElementById("jasdesu4.mp3").play(); }
function ring473() { document.getElementById("jasdesu5.mp3").play(); }
function ring474() { document.getElementById("karasu18.mp3").play(); }
function ring475() { document.getElementById("karasu19.mp3").play(); }
function ring476() { document.getElementById("xtoq.mp3").play(); }
function ring477() { document.getElementById("power.mp3").play(); }
function ring478() { document.getElementById("karasu20.mp3").play(); }
function ring479() { document.getElementById("karasu21.mp3").play(); }
function ring480() { document.getElementById("omoroiyan_yanyan.mp3").play(); }
function ring481() { document.getElementById("naeruna_koe.mp3").play(); }
function ring482() { document.getElementById("omgwtfvdk.mp3").play(); }
function ring483() { document.getElementById("kde.mp3").play(); }
function ring484() { document.getElementById("kontororo.mp3").play(); }
function ring485() { document.getElementById("konbanwa.mp3").play(); }
function ring486() { document.getElementById("ohaou.mp3").play(); }
function ring487() { document.getElementById("sugitagenpaku.mp3").play(); }
function ring488() { document.getElementById("yattaka.mp3").play(); }
function ring489() { document.getElementById("piiman.mp3").play(); }
function ring490() { document.getElementById("gakej1.mp3").play(); }
function ring491() { document.getElementById("kimosagati.mp3").play(); }
function ring492() { document.getElementById("210man.mp3").play(); }
function ring493() { document.getElementById("ichimotsu.mp3").play(); }
function ring494() { document.getElementById("kimosahavip.mp3").play(); }
function ring495() { document.getElementById("torahyou.mp3").play(); }
function ring496() { document.getElementById("detayoshizue.mp3").play(); }
function ring497() { document.getElementById("sizuenoa.mp3").play(); }
function ring498() { document.getElementById("oden.mp3").play(); }
function ring499() { document.getElementById("ggazashitamen.mp3").play(); }
function ring500() { document.getElementById("seichokyokusenegui.mp3").play(); }
function ring501() { document.getElementById("jaspernismoke.mp3").play(); }
function ring502() { document.getElementById("smith_reina.mp3").play(); }
function ring503() { document.getElementById("minna_jasper.mp3").play(); }
function ring504() { document.getElementById("corey.mp3").play(); }
function ring505() { document.getElementById("900dmg.mp3").play(); }
function ring506() { document.getElementById("shaka001.mp3").play(); }
function ring507() { document.getElementById("shaka002.mp3").play(); }
function ring508() { document.getElementById("shaka003.mp3").play(); }
function ring509() { document.getElementById("shaka004.mp3").play(); }
function ring510() { document.getElementById("shaka005.mp3").play(); }
function ring511() { document.getElementById("shaka006.mp3").play(); }
function ring512() { document.getElementById("shaka007.mp3").play(); }
function ring513() { document.getElementById("shaka008.mp3").play(); }
function ring514() { document.getElementById("shaka009.mp3").play(); }
function ring515() { document.getElementById("onegaishimangusu.mp3").play(); }
function ring516() { document.getElementById("bi_con.mp3").play(); }
function ring517() { document.getElementById("shindou_j.mp3").play(); }
function ring518() { document.getElementById("hanketuj.mp3").play(); }
function ring519() { document.getElementById("oppaitoriiko.mp3").play(); }
function ring520() { document.getElementById("smokebonbon.mp3").play(); }
function ring521() { document.getElementById("tsu_smabura.mp3").play(); }
function ring522() { document.getElementById("taej.mp3").play(); }
function ring523() { document.getElementById("zenopa.mp3").play(); }
function ring524() { document.getElementById("omoroiyan001.mp3").play(); }
function ring525() { document.getElementById("omoroiyan002.mp3").play(); }
function ring526() { document.getElementById("omoroiyan003.mp3").play(); }
function ring527() { document.getElementById("omoroiyan004.mp3").play(); }
function ring528() { document.getElementById("omoroiyan005.mp3").play(); }
function ring529() { document.getElementById("janmasuboke.mp3").play(); }
function ring530() { document.getElementById("haihai.mp3").play(); }
function ring531() { document.getElementById("oja001.mp3").play(); }
function ring532() { document.getElementById("oissu.mp3").play(); }
function ring533() { document.getElementById("tsu_chenbar1.mp3").play(); }
function ring534() { document.getElementById("tsu_chenbar2.mp3").play(); }
function ring535() { document.getElementById("toosugiru.mp3").play(); }
function ring536() { document.getElementById("hanketu.mp3").play(); }
function ring537() { document.getElementById("tashimasoujiki.mp3").play(); }
function ring538() { document.getElementById("kanojotukureyo.mp3").play(); }
function ring539() { document.getElementById("wkimotiyo.mp3").play(); }
function ring540() { document.getElementById("shnjukuaruta.mp3").play(); }
function ring541() { document.getElementById("whenishrouduseit001.mp3").play(); }
function ring542() { document.getElementById("whenishrouduseit002.mp3").play(); }
function ring543() { document.getElementById("ohho004.mp3").play(); }
function ring544() { document.getElementById("h_aan.mp3").play(); }
function ring545() { document.getElementById("ult_checkmate.mp3").play(); }
function ring546() { document.getElementById("miruna_yasahisasutero.mp3").play(); }
function ring547() { document.getElementById("okay003.mp3").play(); }
function ring548() { document.getElementById("okay004.mp3").play(); }
function ring549() { document.getElementById("okay005.mp3").play(); }
function ring550() { document.getElementById("nice003.mp3").play(); }
function ring551() { document.getElementById("nice004.mp3").play(); }
function ring552() { document.getElementById("nice005.mp3").play(); }
function ring553() { document.getElementById("nice006.mp3").play(); }
function ring554() { document.getElementById("nice007.mp3").play(); }
function ring555() { document.getElementById("nice008.mp3").play(); }
function ring556() { document.getElementById("nice009.mp3").play(); }
function ring557() { document.getElementById("nice010.mp3").play(); }
function ring558() { document.getElementById("okay006.mp3").play(); }
function ring559() { document.getElementById("pipi.mp3").play(); }
function ring560() { document.getElementById("akarinsub.mp3").play(); }
function ring561() { document.getElementById("koumenoakarin.mp3").play(); }
function ring562() { document.getElementById("omoroiyan006.mp3").play(); }
function ring563() { document.getElementById("omoroiyan007.mp3").play(); }
function ring564() { document.getElementById("dairiten.mp3").play(); }
function ring565() { document.getElementById("majinbuu001.mp3").play(); }
function ring566() { document.getElementById("bouchan.mp3").play(); }
function ring567() { document.getElementById("dudun.mp3").play(); }
function ring568() { document.getElementById("sensuda.mp3").play(); }
function ring569() { document.getElementById("usodaro.mp3").play(); }
function ring570() { document.getElementById("oide.mp3").play(); }
function ring571() { document.getElementById("gyakutanshinfunin.mp3").play(); }
function ring572() { document.getElementById("oomutanooton.mp3").play(); }
function ring573() { document.getElementById("tsu_eakon.mp3").play(); }
function ring574() { document.getElementById("nanisamayonsama.mp3").play(); }
function ring575() { document.getElementById("bakamegane.mp3").play(); }
function ring576() { document.getElementById("gomen.mp3").play(); }
function ring577() { document.getElementById("superbakudan.mp3").play(); }
function ring578() { document.getElementById("pipin.mp3").play(); }
function ring579() { document.getElementById("shakanohoneytrap.mp3").play(); }
function ring580() { document.getElementById("shakatan002.mp3").play(); }
function ring581() { document.getElementById("majinbuu002.mp3").play(); }
function ring582() { document.getElementById("majinbuu003.mp3").play(); }
function ring583() { document.getElementById("jajjinandayone.mp3").play(); }
function ring584() { document.getElementById("lol3.mp3").play(); }
function ring585() { document.getElementById("omoroiyan008.mp3").play(); }
function ring586() { document.getElementById("omoroiyan009.mp3").play(); }
function ring587() { document.getElementById("motitsumotaretsu7.mp3").play(); }
function ring588() { document.getElementById("1234_cn.mp3").play(); }
function ring589() { document.getElementById("bronze2.mp3").play(); }
function ring590() { document.getElementById("batakosan.mp3").play(); }
function ring591() { document.getElementById("abayo.mp3").play(); }
function ring592() { document.getElementById("dottiiku.mp3").play(); }
function ring593() { document.getElementById("corey2.mp3").play(); }
function ring594() { document.getElementById("finalgatilast.mp3").play(); }
function ring595() { document.getElementById("wtf2.mp3").play(); }
function ring596() { document.getElementById("urusee_sonotoori.mp3").play(); }
function ring597() { document.getElementById("karasu22.mp3").play(); }
function ring598() { document.getElementById("fuifui2.mp3").play(); }
function ring599() { document.getElementById("warai003.mp3").play(); }
function ring600() { document.getElementById("rust06_jaskoukuu001.mp3").play(); }
function ring601() { document.getElementById("rust06_jaskoukuu002.mp3").play(); }
function ring602() { document.getElementById("rust06_jaskoukuu003.mp3").play(); }
function ring603() { document.getElementById("rust06_jaskoukuu004.mp3").play(); }
function ring604() { document.getElementById("rust06_jaskoukuu005.mp3").play(); }
function ring605() { document.getElementById("rust06_jaskoukuu006.mp3").play(); }
function ring606() { document.getElementById("rust06_jaskoukuu007.mp3").play(); }
function ring607() { document.getElementById("rust06_jaskoukuu008.mp3").play(); }
function ring608() { document.getElementById("rust06_jaskoukuu009.mp3").play(); }
function ring609() { document.getElementById("rust06_jaskoukuu010.mp3").play(); }
function ring610() { document.getElementById("rust06_jaskoukuu011.mp3").play(); }
function ring611() { document.getElementById("rust06_jaskoukuu012.mp3").play(); }
function ring612() { document.getElementById("rust06_jassann001.mp3").play(); }
function ring613() { document.getElementById("rust06_jassann002.mp3").play(); }
function ring614() { document.getElementById("rust06_jassann003.mp3").play(); }
function ring615() { document.getElementById("rust06_jassann004.mp3").play(); }
function ring616() { document.getElementById("rust06_yoshi001.mp3").play(); }
function ring617() { document.getElementById("rust06_yoshi002.mp3").play(); }
function ring618() { document.getElementById("rust06_yaba.mp3").play(); }
function ring619() { document.getElementById("rust06_wood10.mp3").play(); }
function ring620() { document.getElementById("rust06_tomodachishoukai.mp3").play(); }
function ring621() { document.getElementById("rust06_tashimatransport001.mp3").play(); }
function ring622() { document.getElementById("rust06_tashimatransport002.mp3").play(); }
function ring623() { document.getElementById("rust06_suprise.mp3").play(); }
function ring624() { document.getElementById("rust06_shokaimuryou.mp3").play(); }
function ring625() { document.getElementById("rust06_senkyo001.mp3").play(); }
function ring626() { document.getElementById("rust06_senkyo002.mp3").play(); }
function ring627() { document.getElementById("rust06_koukoku001.mp3").play(); }
function ring628() { document.getElementById("rust06_koukoku002.mp3").play(); }
function ring629() { document.getElementById("rust06_koukoku003.mp3").play(); }
function ring630() { document.getElementById("rust06_koukoku004.mp3").play(); }
function ring631() { document.getElementById("rust06_koukoku005.mp3").play(); }
function ring632() { document.getElementById("rust06_koushuunyuu.mp3").play(); }
function ring633() { document.getElementById("rust06_meiwakudenwa.mp3").play(); }
function ring634() { document.getElementById("rust06_naruhododesune.mp3").play(); }
function ring635() { document.getElementById("rust06_osikkomoresou.mp3").play(); }
function ring636() { document.getElementById("rust06_k5.mp3").play(); }
function ring637() { document.getElementById("rust06_katsudonnok.mp3").play(); }
function ring638() { document.getElementById("rust06_interia.mp3").play(); }
function ring639() { document.getElementById("rust06_iteite.mp3").play(); }
function ring640() { document.getElementById("rust06_fable.mp3").play(); }
function ring641() { document.getElementById("rust06_eigyousaikai.mp3").play(); }
function ring642() { document.getElementById("rust06_deriheri001.mp3").play(); }
function ring643() { document.getElementById("rust06_denwadakehayametekure.mp3").play(); }
function ring644() { document.getElementById("rust06_bgm_vocabulary.mp3").play(); }
function ring645() { document.getElementById("rust06_bgm_bts.mp3").play(); }
function ring646() { document.getElementById("rust06_abunee001.mp3").play(); }
function ring647() { document.getElementById("rust06_abunee002.mp3").play(); }
function ring648() { document.getElementById("rust06_abunee003.mp3").play(); }
function ring649() { document.getElementById("tar_001.mp3").play(); }
function ring650() { document.getElementById("tar_002.mp3").play(); }
function ring651() { document.getElementById("tar_003.mp3").play(); }
function ring652() { document.getElementById("tar_004.mp3").play(); }
function ring653() { document.getElementById("tar_005.mp3").play(); }
function ring654() { document.getElementById("tar_006.mp3").play(); }
function ring655() { document.getElementById("tar_007.mp3").play(); }
function ring656() { document.getElementById("tar_008.mp3").play(); }
function ring657() { document.getElementById("tar_009.mp3").play(); }
function ring658() { document.getElementById("tar_010.mp3").play(); }
function ring659() { document.getElementById("tar_011.mp3").play(); }
function ring660() { document.getElementById("tar_012.mp3").play(); }
function ring661() { document.getElementById("tar_013.mp3").play(); }
function ring662() { document.getElementById("tar_014.mp3").play(); }
function ring663() { document.getElementById("tar_015.mp3").play(); }
function ring664() { document.getElementById("tar_016.mp3").play(); }
function ring665() { document.getElementById("tar_017.mp3").play(); }
function ring666() { document.getElementById("roren001.mp3").play(); }
function ring667() { document.getElementById("roren002.mp3").play(); }
function ring668() { document.getElementById("roren003.mp3").play(); }
function ring669() { document.getElementById("roren004.mp3").play(); }
function ring670() { document.getElementById("roren005.mp3").play(); }
function ring671() { document.getElementById("kirua001.mp3").play(); }
function ring672() { document.getElementById("ojihara001.mp3").play(); }
function ring673() { document.getElementById("umasugiteheta.mp3").play(); }
function ring674() { document.getElementById("soudayone.mp3").play(); }
function ring675() { document.getElementById("omoroiyan010.mp3").play(); }
function ring676() { document.getElementById("tuukaku_link.mp3").play(); }
function ring677() { document.getElementById("oja002.mp3").play(); }
function ring678() { document.getElementById("oja003.mp3").play(); }
function ring679() { document.getElementById("chonun_keigo_imunida.mp3").play(); }
function ring680() { document.getElementById("oreno_onepick.mp3").play(); }
function ring681() { document.getElementById("ohho006.mp3").play(); }
function ring682() { document.getElementById("ohho007.mp3").play(); }
function ring683() { document.getElementById("ohho008.mp3").play(); }
function ring684() { document.getElementById("ohayou1.mp3").play(); }
function ring685() { document.getElementById("yaroya001.mp3").play(); }
function ring686() { document.getElementById("yaroya002.mp3").play(); }
function ring687() { document.getElementById("yaroya003.mp3").play(); }
function ring688() { document.getElementById("yaroya004.mp3").play(); }
function ring689() { document.getElementById("yaroya005.mp3").play(); }
function ring690() { document.getElementById("omoroiyan011.mp3").play(); }
function ring691() { document.getElementById("omoroiyan012.mp3").play(); }
function ring692() { document.getElementById("omoroiyan013.mp3").play(); }
function ring693() { document.getElementById("okay007.mp3").play(); }
function ring694() { document.getElementById("jasperugg.mp3").play(); }
function ring695() { document.getElementById("123_kr.mp3").play(); }
function ring696() { document.getElementById("roren006.mp3").play(); }
function ring697() { document.getElementById("roren007.mp3").play(); }
