// sound files
function ring1() { document.getElementById("oshigotoOtsukaresama_sasayaki.mp3").play(); }
function ring2() { document.getElementById("oyasuminasai_sasayaki.mp3").play(); }
function ring3() { document.getElementById("1syukanOtsukaresama.mp3").play(); }
function ring4() { document.getElementById("aruchuCaffeechuPomenimuchu.mp3").play(); }
function ring5() { document.getElementById("hanamizuZubizubiRikochan.mp3").play(); }
function ring6() { document.getElementById("konbanha.mp3").play(); }
function ring7() { document.getElementById("oyasumi.mp3").play(); }
function ring8() { document.getElementById("oyasumi_hanagoe.mp3").play(); }
function ring9() { document.getElementById("RikoNote.mp3").play(); }
function ring10() { document.getElementById("baka.mp3").play(); }
function ring11() { document.getElementById("barebaredayo.mp3").play(); }
function ring12() { document.getElementById("butigire.mp3").play(); }
function ring13() { document.getElementById("capcomYorosiku.mp3").play(); }
function ring14() { document.getElementById("choshieena.mp3").play(); }
function ring15() { document.getElementById("chottoMaji.mp3").play(); }
function ring16() { document.getElementById("damatteMattokeAHO.mp3").play(); }
function ring17() { document.getElementById("fullHPChu.mp3").play(); }
function ring18() { document.getElementById("gomenNasaiYurushite.mp3").play(); }
function ring19() { document.getElementById("hayakuchi.mp3").play(); }
function ring20() { document.getElementById("jikoshokai.mp3").play(); }
function ring21() { document.getElementById("kimo.mp3").play(); }
function ring22() { document.getElementById("kimochiwarui.mp3").play(); }
function ring23() { document.getElementById("konitiwa.mp3").play(); }
function ring24() { document.getElementById("kusogayo.mp3").play(); }
function ring25() { document.getElementById("onegaisimasu.mp3").play(); }
function ring26() { document.getElementById("sya-naina-.mp3").play(); }
function ring27() { document.getElementById("tadaima.mp3").play(); }
function ring28() { document.getElementById("uchutoKoshin.mp3").play(); }
function ring29() { document.getElementById("konnichiha_echo.mp3").play(); }
function ring30() { document.getElementById("arigatone.mp3").play(); }
function ring31() { document.getElementById("arigatone2.mp3").play(); }
function ring32() { document.getElementById("kochirakosoKansha.mp3").play(); }
function ring33() { document.getElementById("usojan.mp3").play(); }
function ring34() { document.getElementById("daipan.mp3").play(); }
function ring35() { document.getElementById("killjoy.mp3").play(); }
function ring36() { document.getElementById("reyna.mp3").play(); }
function ring37() { document.getElementById("CT2.mp3").play(); }
function ring38() { document.getElementById("fadeA.mp3").play(); }
function ring39() { document.getElementById("migikurisikaKatan.mp3").play(); }
function ring40() { document.getElementById("nice.mp3").play(); }
function ring41() { document.getElementById("recon.mp3").play(); }
function ring42() { document.getElementById("tsuyo.mp3").play(); }
function ring43() { document.getElementById("haratatsu.mp3").play(); }
function ring44() { document.getElementById("uxufu.mp3").play(); }
function ring45() { document.getElementById("ohayou.mp3").play(); }
function ring46() { document.getElementById("kathiyan.mp3").play(); }
function ring47() { document.getElementById("matteYaba.mp3").play(); }
function ring48() { document.getElementById("naorukana.mp3").play(); }
function ring49() { document.getElementById("souiukotomoAruyone.mp3").play(); }
function ring50() { document.getElementById("BHannou.mp3").play(); }
function ring51() { document.getElementById("BOoi.mp3").play(); }
function ring52() { document.getElementById("classic.mp3").play(); }
function ring53() { document.getElementById("curtainAgetehoshiikamo.mp3").play(); }
function ring54() { document.getElementById("ha-deka.mp3").play(); }
function ring55() { document.getElementById("long2.mp3").play(); }
function ring56() { document.getElementById("nice2.mp3").play(); }
function ring57() { document.getElementById("niceNice.mp3").play(); }
function ring58() { document.getElementById("NiceNice_report.mp3").play(); }
function ring59() { document.getElementById("short.mp3").play(); }
function ring60() { document.getElementById("siteSage.mp3").play(); }
function ring61() { document.getElementById("spikeOchiteru.mp3").play(); }
function ring62() { document.getElementById("rikorikori.mp3").play(); }
function ring63() { document.getElementById("samishiinndakedo.mp3").play(); }
function ring64() { document.getElementById("genkiDayo.mp3").play(); }
function ring65() { document.getElementById("hello.mp3").play(); }
function ring66() { document.getElementById("konichiwa2.mp3").play(); }
function ring67() { document.getElementById("minnaOhayoGenkinishitetaKinouNanishita.mp3").play(); }
function ring68() { document.getElementById("ohayou2.mp3").play(); }
function ring69() { document.getElementById("ohayou3.mp3").play(); }
function ring70() { document.getElementById("jettCT.mp3").play(); }
function ring71() { document.getElementById("jettDead.mp3").play(); }
function ring72() { document.getElementById("gomennasai.mp3").play(); }
function ring73() { document.getElementById("kusoga.mp3").play(); }
function ring74() { document.getElementById("moriagatteIkouze.mp3").play(); }
function ring75() { document.getElementById("nandeyanen.mp3").play(); }

function ring76() { document.getElementById("arenanokaSorenanoka.mp3").play(); }
function ring77() { document.getElementById("dottiDotti.mp3").play(); }
function ring78() { document.getElementById("dousiyo.mp3").play(); }
function ring79() { document.getElementById("kuukiyometenaiyoAnmari.mp3").play(); }
